/** Worker entry: OpenNext's handler plus our Durable Object classes.
 * (wrangler `main` points here; OpenNext output is re-exported.) */

// Generated by `opennextjs-cloudflare build`; this file is excluded from
// tsconfig (wrangler bundles it with esbuild).
import handler from "./.open-next/worker.js";
import { SyncJournal as OpLog } from "durable-sync/server";
import { handleTombstones } from "./src/server/tombstones";

/** One instance per user (idFromName(email)): the single-threaded
 * consistency point that orders that user's sync ops.
 *
 * The log itself is durable-sync — push, pull, epochs, reset. All we add is
 * the one thing it can't know: what a `deleteWorkout` op deleted. It never
 * interprets payloads, which is exactly what keeps it a primitive.
 *
 * The class name is unchanged, so the existing Durable Object and its
 * migration tag carry straight over — and the SQL schema is byte-identical,
 * so the live journal survives with no migration.
 */
export class SyncJournal extends OpLog {
  async fetch(request: Request): Promise<Response> {
    // The backup merge unions rows and so can never drop one; the journal is
    // the only authority on what was deleted.
    if (new URL(request.url).pathname === "/tombstones") {
      return Response.json(handleTombstones(this.store));
    }
    return super.fetch(request);
  }
}

export default handler;
