/** Worker entry: OpenNext's handler plus our Durable Object classes.
 * (wrangler `main` points here; OpenNext output is re-exported.) */

// Generated by `opennextjs-cloudflare build`; this file is excluded from
// tsconfig (wrangler bundles it with esbuild).
import handler from "./.open-next/worker.js";
import {
  SqlOpStore,
  handlePush,
  handlePull,
  handleReset,
  type JournalOp,
} from "./src/server/syncJournal";
import type { SqlLike } from "./src/server/syncJournal";

interface DurableObjectStateLike {
  storage: { sql: SqlLike };
}

/** One instance per user (idFromName(email)): the single-threaded
 * consistency point that orders that user's sync ops. */
export class SyncJournal {
  private store: SqlOpStore;

  constructor(state: DurableObjectStateLike) {
    this.store = new SqlOpStore(state.storage.sql);
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === "POST") {
      const body = (await request.json().catch(() => null)) as { ops?: JournalOp[] } | null;
      return Response.json(handlePush(this.store, body?.ops ?? []));
    }
    // Maintenance escape hatch for an append-only log. NOT public: /api/sync
    // serves only GET and POST, so reaching this needs the DO binding.
    if (request.method === "DELETE") {
      return Response.json(handleReset(this.store));
    }
    const since = Number(url.searchParams.get("since") ?? 0) || 0;
    return Response.json(handlePull(this.store, since));
  }
}

export default handler;
